Added restaurant show pages with reviews
pekkmj/radical-restaurant-reviews pull request #3
Opened 2023-02-01 21:32 UTC by vkk5252

Implemented: 
- restaurant show component
- review list component
- review tile component
- reviews migration
- association between restaurants and reviews tables
- GET api endpoint for restaurant + reviews
- restaurant tiles now link to show pages

Other changes:
- changed indent spacing size to 2
- added a button to go back to the index page from the show page
- centered new restaurant form

2023-02-01 21:54 UTC, Epinto150 reviewed
I think the PR looks good!

2023-02-01 21:56 UTC, nwalberts requested changes

2023-02-01 21:56 UTC, nwalberts commented on server/src/routes/api/v1/RestaurantRouter.js
> +        restaurant.reviews = await restaurant.$relatedQuery("reviews")
please serialize your reviews as well

2023-02-02 20:05 UTC, nwalberts requested changes

2023-02-02 20:05 UTC, nwalberts commented on server/src/db/seeders/ReviewSeeder.js
> +        body: "adsdsa",
no dummy data, replace this with an actual fake Review `body`

2023-02-02 20:05 UTC, nwalberts commented on server/src/serializers/RestaurantSerializer.js
> +      relatedReviews.map(review => ReviewSerializer.getSummary(review))
you do not need Promise.all here

2023-02-02 20:54 UTC, merged